#!/bin/bash

SCRIPT_FILE="./scripts/commander_script_autogenerated.jlink"

echo "usb" 		>  $SCRIPT_FILE
echo "r" 		>> $SCRIPT_FILE
echo "u Kinetis" 	>> $SCRIPT_FILE
echo "usb" 		>> $SCRIPT_FILE
echo "r" 		>> $SCRIPT_FILE
echo "erase" 		>> $SCRIPT_FILE
echo "loadbin $1, 0"	>> $SCRIPT_FILE
echo "q" 		>> $SCRIPT_FILE

JLinkExe -if swd -device MK20DX256xxx7 -autoconnect 1 -speed 1000 -CommanderScript $SCRIPT_FILE

